server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        # Route pour accéder à la console H2 du product-service
        - id: product-service-h2-console
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-h2-console/**
          filters:
            - StripPrefix=1  # Enlève /product-h2-console pour avoir /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"  # expose routes, health, metrics
  endpoint:
    gateway:
      enabled: true  # Active explicitement l'endpoint gateway
